// <auto-generated />
using System;
using FundooRepositoryLayer.ModelContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundooRepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200115133542_SeedUserDataEmailCheck")]
    partial class SeedUserDataEmailCheck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FundooCommonLayer.ModelDB.UserDetails", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("EmailId")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<DateTime>("ModifiedAt");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.ToTable("UserDetails");

                    b.HasData(
                        new { UserId = new Guid("af1e0f0a-f4d8-404a-b346-d2970c4079fb"), CreatedAt = new DateTime(2020, 1, 15, 19, 5, 42, 677, DateTimeKind.Local), EmailId = "rahulchaurasia@hotmail.com", FirstName = "Rahul", IsActive = true, LastName = "Chaurasia", ModifiedAt = new DateTime(2020, 1, 15, 19, 5, 42, 677, DateTimeKind.Local), Password = "123456789", Type = "Basic" },
                        new { UserId = new Guid("7cc7fcb3-d6c0-4984-96d7-b4459ac0cc2f"), CreatedAt = new DateTime(2020, 1, 15, 19, 5, 42, 677, DateTimeKind.Local), EmailId = "rahulchaurasia92@hotmail.com", FirstName = "Rahul", IsActive = true, LastName = "Chaurasia", ModifiedAt = new DateTime(2020, 1, 15, 19, 5, 42, 677, DateTimeKind.Local), Password = "123456789", Type = "Advanced" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
